"""
Characterization tests for evaluate_result and _evaluate_manifest_result.

Captures EXACT (verdict, evaluation) output for a fixture set of synthetic
result dicts, generated by calling the real functions on the current main
and recording their output in tests/fixtures/char_fixtures.json.

These tests lock the current behavior so that refactoring can proceed
safely: after any refactor, every fixture must still produce the exact
same (verdict, evaluation) output.
"""

import json
import sys
import tempfile
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from autonomous_loop import evaluate_result, _evaluate_manifest_result, load_knowledge
from backlog import Backlog, make_param_entry


FIXTURES_PATH = Path(__file__).resolve().parent / "fixtures" / "char_fixtures.json"


def _load_fixtures():
    with open(FIXTURES_PATH) as f:
        return json.load(f)


# ──────────────────────────────────────────────
# evaluate_result fixtures
# ──────────────────────────────────────────────

class TestEvaluateResultCharacterization:
    """Every evaluate_result fixture must produce identical output."""

    FIXTURES = _load_fixtures()

    # --- Error taxonomy ---

    def test_infra_error(self):
        f = self.FIXTURES["infra_error"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_code_error(self):
        f = self.FIXTURES["code_error"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_unknown_error(self):
        f = self.FIXTURES["unknown_error"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_missing_error_type(self):
        f = self.FIXTURES["missing_error_type"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_walkforward_disabled(self):
        f = self.FIXTURES["walkforward_disabled"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    # --- Gate failures ---

    def test_val_gate_fail_sharpe(self):
        f = self.FIXTURES["val_gate_fail_sharpe"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_val_gate_fail_drawdown(self):
        f = self.FIXTURES["val_gate_fail_drawdown"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_holdout_fail(self):
        f = self.FIXTURES["holdout_fail"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_full_adoption(self):
        f = self.FIXTURES["full_adoption"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        # cluster_id is random, mask it for comparison
        expected = dict(f["evaluation"])
        actual = dict(evaluation)
        assert "cluster_id" in actual, "adopted evaluation must have cluster_id"
        expected.pop("cluster_id", None)
        actual.pop("cluster_id", None)
        assert actual == expected

    def test_near_miss_drawdown(self):
        f = self.FIXTURES["near_miss_drawdown"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    # --- Knowledge-state-dependent fixtures (round-trip disk) ---
    # These don't go in the snapshot-based FIXTURES because cluster dedup
    # requires actual knowledge state on disk.

    def test_full_adoption_disk_roundtrip(self, tmp_path, monkeypatch):
        """Full adoption with knowledge written/read from disk."""
        kf = tmp_path / "knowledge.json"
        monkeypatch.setattr("autonomous_loop.KNOWLEDGE_FILE", kf)

        knowledge = _fresh_knowledge()
        # Save empty knowledge to disk so evaluate_result can find it
        kf.write_text(json.dumps(knowledge))

        f = self.FIXTURES["full_adoption"]
        hyp = _make_hypothesis()
        verdict, evaluation = evaluate_result(hyp, f["result"], knowledge)

        assert verdict == "adopted"
        assert evaluation["verdict"] == "adopted"
        assert evaluation["sharpe_ratio"] == 1.2
        assert evaluation["holdout_sharpe"] == 0.8
        assert evaluation["gate_results"]["validation"] is True
        assert evaluation["gate_results"]["holdout"] is True
        assert evaluation["gate_results"]["cluster"] == "new"
        assert "🏆 ALL GATES PASSED" in evaluation["reasons"][0]
        assert "cluster_id" in evaluation


# ──────────────────────────────────────────────
# _evaluate_manifest_result fixtures
# ──────────────────────────────────────────────

class TestManifestEvaluateCharacterization:
    """Every _evaluate_manifest_result fixture must produce identical output."""

    FIXTURES = _load_fixtures()

    def test_missing_metrics(self):
        f = self.FIXTURES["manifest_missing_metrics"]
        hyp = _make_manifest_hypothesis()
        verdict, evaluation = _evaluate_manifest_result(f["runner_result"], hyp, _fresh_knowledge())
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_adopted(self):
        f = self.FIXTURES["manifest_adopted"]
        hyp = _make_manifest_hypothesis()
        knowledge = _fresh_knowledge()
        knowledge["families"] = {"manifest:test_strat|universe:abcdef12": {"n_trials": 0}}
        verdict, evaluation = _evaluate_manifest_result(f["runner_result"], hyp, knowledge)
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_val_fail(self):
        f = self.FIXTURES["manifest_val_fail"]
        hyp = _make_manifest_hypothesis()
        knowledge = _fresh_knowledge()
        knowledge["families"] = {"manifest:test_strat|universe:abcdef12": {"n_trials": 0}}
        verdict, evaluation = _evaluate_manifest_result(f["runner_result"], hyp, knowledge)
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_holdout_fail(self):
        f = self.FIXTURES["manifest_holdout_fail"]
        hyp = _make_manifest_hypothesis()
        knowledge = _fresh_knowledge()
        knowledge["families"] = {"manifest:test_strat|universe:abcdef12": {"n_trials": 0}}
        verdict, evaluation = _evaluate_manifest_result(f["runner_result"], hyp, knowledge)
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]

    def test_expert_extras(self):
        f = self.FIXTURES["manifest_expert_extras"]
        hyp = _make_manifest_hypothesis()
        knowledge = _fresh_knowledge()
        knowledge["families"] = {"manifest:test_strat|universe:abcdef12": {"n_trials": 0}}
        verdict, evaluation = _evaluate_manifest_result(f["runner_result"], hyp, knowledge)
        assert verdict == f["verdict"]
        assert evaluation == f["evaluation"]


# ──────────────────────────────────────────────
# helpers
# ──────────────────────────────────────────────

def _make_hypothesis(strategy="sma_crossover", symbol="AAPL", params=None):
    if params is None:
        params = {"fast_window": 10, "slow_window": 30}
    return {
        "id": "char_test_001",
        "strategy": strategy,
        "symbol": symbol,
        "params": params,
        "description": "test",
        "generated_at": "2026-01-01T00:00:00",
    }


def _make_manifest_hypothesis():
    return {
        "id": "bl_char_manifest",
        "strategy": "manifest:test_strat",
        "symbol": "universe:abcdef12",
        "params": {"universe_size": 5, "execution_mode": "structured", "primary_metric": "sharpe"},
        "description": "test",
        "generated_at": "2026-01-01T00:00:00",
    }


def _fresh_knowledge():
    return {
        "tested": [], "tested_combinations": [], "adopted": [], "rejected": [],
        "superseded": [], "families": {}, "iterations": 0, "errors": [],
    }
